#!/bin/bash

# xrdb -merge .Xresources; xrdb -merge .xdefaults

# Load keboard remap if it doesn't load automatically
# xmodmap .xmodmap

# trayer systray
trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 10 --height 16 --transparent true --tint 0x000000 &

# FIXME stalone systray
# clickable, unlike trayer, but for some reason causes bug at login.
# stalonetray --background black --dockapp-mode simple --geometry 3x1-2 --icon-size 16 &

nautilus -n &

clipit &

dropbox start &

exec xmonad
